### ISSUE TITLE
멤버 엔티티 개발

### ISSUE THREAD

**Issue by Drum-J** [jaws-projects/jaws#2]
## 📄 Describe
멤버 엔티티 개발하기

## ✅ Tasks
- [x] 이슈 생성
- [x] feat/멤버 엔티티 브랜치 생성
- [x] Member 클래스 작성
- [x] Member 관련 엔티티 정리
- [x] PR & merge

**Comment by Drum-J** [comment]
#3 리뷰 확인! 수정 필요한 부분은 다음 PR에 같이 올리기
