### ISSUE TITLE
스터디 생성 로직

### ISSUE THREAD

**Issue by kyunghyun-Park** [jaws-projects/jaws#7]
## 📄 Describe
스터디 엔티티 생성, 
스터디 생성 로직 구현

## ✅ Tasks
- [ ] 이슈 생성
- [ ] 스터디 엔티티 생성
- [ ] 스터디 생성 화면 구현
- [ ] 스터디 생성 api 개발
- [ ] PR & merge
